"""Multiprocessing executor adapter for backward compatibility.

本模块将所有执行信道能力直接委托并导出自 tasklite.engine.channel，
保留向后兼容的符号导出以支持历史测试与外部引用。
"""

from __future__ import annotations

from ..utils.ipc import (
    append_input,
    append_output,
    append_signal,
    inputs_path,
    outputs_path,
    signals_path,
)
from .channel import (
    AbortOutcome,
    ArtifactCleanupMode,
    ExecutionChannel,
    ExecutionChannelProtocol,
    ExecutionHandle,
    ExecutionResult,
    JobHandle,
    MultiprocessingExecutor,
    _decode_ipc_result,
    _decode_raw_result,
    _encode_raw_result,
    _iter_stale_result_paths,
    _mp_worker_wrapper,
    _normalize_handler_result,
    _write_result_with_degradation,
    _INCARNATION_RE,
    _KEY_TRACEBACK,
    _RAW_TUPLE_SENTINEL,
    _RESULT_DIR_ENV,
    _RESULT_SUFFIX,
    _RESULT_TMP_SUFFIX,
    cleanup_ipc_files,
    read_inputs,
    read_outputs,
    read_result_file,
    read_signals,
    result_path,
    result_tmp_path,
    write_result_atomic,
)

__all__ = [
    "AbortOutcome",
    "ArtifactCleanupMode",
    "ExecutionChannel",
    "ExecutionChannelProtocol",
    "ExecutionHandle",
    "ExecutionResult",
    "JobHandle",
    "MultiprocessingExecutor",
    "_decode_ipc_result",
    "_decode_raw_result",
    "_encode_raw_result",
    "_iter_stale_result_paths",
    "_mp_worker_wrapper",
    "_normalize_handler_result",
    "_write_result_with_degradation",
    "_INCARNATION_RE",
    "_KEY_TRACEBACK",
    "_RAW_TUPLE_SENTINEL",
    "_RESULT_DIR_ENV",
    "_RESULT_SUFFIX",
    "_RESULT_TMP_SUFFIX",
    "append_input",
    "append_output",
    "append_signal",
    "cleanup_ipc_files",
    "inputs_path",
    "outputs_path",
    "read_inputs",
    "read_outputs",
    "read_result_file",
    "read_signals",
    "result_path",
    "result_tmp_path",
    "signals_path",
    "write_result_atomic",
]
